In [ ]:
"let's coding"000000000000

In [1]:
l=[1,3,"agyd",56]
e=[567,7,6]
print(l+e)

[1, 3, 'agyd', 56, 567, 7, 6]


In [4]:
str1="codeunnati"



In [5]:
str1[::2]


'cdunt'

In [6]:
import string
string.ascii_uppercase


'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [7]:
string.ascii_lowercase

'abcdefghijklmnopqrstuvwxyz'

In [95]:
set(string.ascii_lowercase)

{'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [9]:
tuple1=(1,2,3,"mango",34)
tuple2=("Apple",1,5,7)
print(tuple1+tuple2)

(1, 2, 3, 'mango', 34, 'Apple', 1, 5, 7)


In [12]:
dictionary1={1,23,"Cherry",111}
dictionary2={12,13,14,15,"Banana",33}
dictionary1
    

{1, 111, 23, 'Cherry'}

In [22]:
dict1={}
dict1["Name"]="Naumaan"
dict1["Age"]=21
dict1["Programe"]="B.Tech_I.T"
dict1["Number"]=12


In [23]:
dict1[0]

KeyError: 0

In [24]:
dict1["Name"]

'Naumaan'

dict1.keys()


In [25]:
dict1.keys()


dict_keys(['Name', 'Age', 'Programe', 'Number'])

In [26]:
dict1.values()

dict_values(['Naumaan', 21, 'B.Tech_I.T', 12])

In [29]:
dict2={}
dict2[1]=1
dict2[100]=100

In [28]:
dict2

{1: 1, 100: 100}

In [30]:
dict2[1,52]=102

In [31]:
dict2

{1: 1, 100: 100, (1, 52): 102}

In [34]:
my_set={1,2,3}
print(my_set)

{1, 2, 3}


In [35]:
set1={1,2,3,4,5}

In [36]:
set1

{1, 2, 3, 4, 5}

In [37]:
set1[0]

TypeError: 'set' object is not subscriptable

In [39]:
set2={3,5,7,9,11}
set1|set2

{1, 2, 3, 4, 5, 7, 9, 11}

In [40]:
set1,set2

({1, 2, 3, 4, 5}, {3, 5, 7, 9, 11})

In [43]:
set1&set2

{3, 5}

In [44]:
set1.union(set2)

{1, 2, 3, 4, 5, 7, 9, 11}

In [45]:
set2.intersection(set1)

{3, 5}

In [46]:
set1-set2

{1, 2, 4}

In [47]:
type(set1)

set

In [48]:
set3={} //because 
type(set3)

dict

In [49]:
set4=set()
type(set4)

set

In [50]:
set5={()}
type(set5)

set

In [52]:
set6={[1,3,56,89]}
set6

TypeError: unhashable type: 'list'

In [55]:
a=50
b=25
if(a>b):
    print("a is greater")
elif(a<b):
    print("b is greater")
else:
    print("Both are Eual")

a is greater


In [56]:
fruits=["Apple","Kiwi","Avocado","Bnanana"]



In [57]:
for i in fruits:
    print(i)

Apple
Kiwi
Avocado
Bnanana


In [59]:
for i in range(5):
    print(i)

0
1
2
3
4


In [61]:
for i in range(5):
    print(i,end="")

01234

In [77]:
def func(a=11,b,c):
    print(a)
    print("Function Body")

SyntaxError: non-default argument follows default argument (3385993721.py, line 1)

In [85]:
func()
print(a)

10
Function Body
10


In [105]:
del a

In [93]:
a=10
def func():
    print(a)
    print("Function Body")
    
func()


10
Function Body


In [106]:
def func():
    print(a)
    print("Function Body")
    

In [107]:
func()
a=10

NameError: name 'a' is not defined

In [87]:
a=10
def func():
    a=a+1
    print(a)
    print("Function Body")
    
func()
print(a)



UnboundLocalError: local variable 'a' referenced before assignment

In [103]:
a=10
def func():
    global a
    a=a+1
    print(a)
    print("Function Body")
    
func()
print(a)



11
Function Body
11


In [123]:
message="The quick browm fox jumps over the lazy dog"
count = message.count("abc")
print("The Count is:...",count)

The Count is:... 0


In [111]:
a={1,2,3,4,5}
b={2,3,4}

In [114]:
a>=b #proper subset of a

True

In [145]:
grade=int(input(("Enter the marks:  ")))
if (grade>=90):
    print("Grade:A")
elif(grade <=89 and grade>=75):
    print("Grade:B")
elif(grade <=74 and grade>=60):
    print("Grade:C")
elif(grade <=59 and grade>=45):
    print("Grade:D")
elif(grade <=45 and grade>=36):
    print("Grade:E")
elif(grade <=35):
    print("Grade:Fail")
    
    

Enter the marks:  85
Grade:B


In [147]:
a=[1,3,5,7,9,11,13]
max(a)


13

In [171]:
import sys

def findMax(arr,n):
    maxFirst = -sys.maxsize -1
    mid = n//2;
    for i in range(0,mid):
        maxFirst = max(maxFirst, arr[i])
    if (n%2==1):
        maxFirst =  max(maxFirst, arr[mid])
    maxSecond = -sys.maxsize - 1
    for i in range(mid,n):
        maxSecond = max(maxSecond, arr[i])
        print(maxFirst, ",",maxSecond)
arr= [1,32,55,56,21]
n = len(arr)
findMax(arr, n)
    

55 , 55
55 , 56
55 , 56


In [172]:
import numpy as np
cric_data=np.loadtxt("https://raw.githubusercontent.com/goradbj/MachineLearning/main/cric.tsv" , skiprows=1)
cric_data

OSError: https://raw.githubusercontent.com/goradbj/MachineLearning/main/cric.tsv not found.

In [185]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [186]:
print(arr.ndim)

2


In [178]:
arr[1][1]

6

In [187]:
print(arr.shape)

(2, 4)


In [190]:
arr=np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr)

[[[1 2 3 4]
  [5 6 7 8]]]


In [191]:
print(arr.ndim)

3


In [192]:
print(arr.shape)


(1, 2, 4)


In [193]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [194]:
print(arr.ndim)

3


In [195]:
print(arr.shape)

(2, 2, 2)


In [199]:
from numpy import random
random.seed(20)
x = random.randint(1,11)
print(x)

4


In [200]:
random.randint(100,size=(20))

array([90, 15, 95, 28, 90,  9, 20, 75, 22, 71, 34, 96, 40, 85, 90, 26, 83,
       16, 62, 16])

In [202]:
from numpy import random
x = random.randint(100,size=(10,5))
print(x)

[[ 4 27 75  8  6]
 [26 79 82 78 10]
 [33 85 17 40 82]
 [42 60 84 30 36]
 [ 8 48 19 48 95]
 [53 10 38  9 60]
 [60 23 52 96 76]
 [78 95 54 81 73]
 [27 39 87  9 14]
 [31 56 56 58 79]]
